# Generated by Django 4.2.1 on 2023-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_category_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_categories',
            field=models.ManyToManyField(to='portfolio.subcategory'),
        ),
    ]
